### ISSUE TITLE
ImportError: No module named libpydenseflow

### ISSUE THREAD

**Issue by wandering007** [yjxiong/anet2016-cuhk#1]
After building everything, I tried to test the code `python examples/classify_video.py data/plastering.avi`.  
The error information shown as following:
```
Traceback (most recent call last):
  File "examples/classify_video.py", line 17, in <module>
    from pyActionRec.action_classifier import ActionClassifier
  File "/home/changmao/actionRec/anet2016-cuhk/pyActionRec/action_classifier.py", line 3, in <module>
    from action_flow import FlowExtractor
  File "/home/changmao/actionRec/anet2016-cuhk/pyActionRec/action_flow.py", line 7, in <module>
    from libpydenseflow import TVL1FlowExtractor
ImportError: No module named libpydenseflow
```
I think that `denseflow` project should be added. But I built it with segmentation fault errors...

**Comment by yjxiong** [comment]
@wandering007 

Did you manage to build opencv and Denseflow?  It seems that the denseflow python interface is missing.

**Comment by wandering007** [comment]
@yjxiong But I built Denseflow with errors...I may create a new issue in Denseflow repository,,,

**Comment by wandering007** [comment]
@yjxiong I cannot build Denseflow right...
```
See <file:///usr/share/doc/gcc-4.6/README.Bugs> for instructions.
In file included from /home/changmao/actionRec/anet2016-cuhk/lib/dense_flow/include/dense_flow.h:9:0,
                 from /home/changmao/actionRec/anet2016-cuhk/lib/dense_flow/src/dense_warp_flow_gpu.cpp:2:
/home/changmao/actionRec/anet2016-cuhk/lib/dense_flow/include/easylogging++/src/easylogging++.h: In function ‘el::base::type::EnumType el::base::utils::bitwise::And(Enum, el::base::type::EnumType) [with Enum = el::base::FormatFlags, el::base::type::EnumType = short unsigned int]’:
/home/changmao/actionRec/anet2016-cuhk/lib/dense_flow/include/easylogging++/src/easylogging++.h:935:55:   instantiated from ‘bool el::base::utils::hasFlag(Enum, el::base::type::EnumType) [with Enum = el::base::FormatFlags, el::base::type::EnumType = short unsigned int]’
/home/changmao/actionRec/anet2016-cuhk/lib/dense_flow/include/easylogging++/src/easylogging++.h:2228:50:   instantiated from here
/home/changmao/actionRec/anet2016-cuhk/lib/dense_flow/include/easylogging++/src/easylogging++.h:914:89: internal compiler error: Segmentation fault
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.6/README.Bugs> for instructions.
Preprocessed source stored into /tmp/ccErMcVo.out file, please attach this to your bugreport.
ERROR: Cannot create report: [Errno 17] File exists: '/var/crash/_usr_lib_gcc_x86_64-linux-gnu_4.6_cc1plus.1023.crash'
make[2]: *** [CMakeFiles/denseflow.dir/src/dense_flow.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
Preprocessed source stored into /tmp/ccndH3ap.out file, please attach this to your bugreport.
ERROR: Cannot create report: [Errno 17] File exists: '/var/crash/_usr_lib_gcc_x86_64-linux-gnu_4.6_cc1plus.1023.crash'
make[2]: *** [CMakeFiles/denseflow.dir/src/zip_utils.cpp.o] Error 1
Preprocessed source stored into /tmp/ccic01Cu.out file, please attach this to your bugreport.
ERROR: Cannot create report: [Errno 17] File exists: '/var/crash/_usr_lib_gcc_x86_64-linux-gnu_4.6_cc1plus.1023.crash'
make[2]: *** [CMakeFiles/denseflow.dir/src/dense_flow_gpu.cpp.o] Error 1
Preprocessed source stored into /tmp/ccMNfrov.out file, please attach this to your bugreport.
ERROR: Cannot create report: [Errno 17] File exists: '/var/crash/_usr_lib_gcc_x86_64-linux-gnu_4.6_cc1plus.1023.crash'
make[2]: *** [CMakeFiles/denseflow.dir/src/dense_warp_flow_gpu.cpp.o] Error 1
make[1]: *** [CMakeFiles/denseflow.dir/all] Error 2
make: *** [all] Error 2

```

**Comment by yjxiong** [comment]
No idea what's wrong with the compiler. Maybe try another version of GCC.

**Comment by wandering007** [comment]
@yjxiong Thanks. I set `cmake .. -DCMAKE_CXX_COMPILER=g++-4.8 -DCMAKE_CC_COMPILER=gcc-4.8` and built it correctly.

**Comment by asafarevich** [comment]
@wandering007  did you put that command into the `build_all.sh` script? I ran into the same issue, tried appending cmake command inside of `build_all.sh` but no luck.

**Comment by itsuncheng** [comment]
I ran into the same error "ImportError: No module named libpydenseflow". My opencv and denseflow are successfully installed, but I still meet an import error. Is this issue related to the path. Should I point the system path environment variable to where denseflow is installed? Would appreciate if you could answer even though this research has been a while!
