### ISSUE TITLE
The demo website was closed ?

### ISSUE THREAD

**Issue by wwdok** [yjxiong/anet2016-cuhk#39]
I can not open the demo website, anyone has the same issue ?
So i try to run it locally, but i came across an error : 

```
(base) weidawang@weidawang-TUF-Gaming-FX506LU-FX506LU:/media/weidawang/DATA/Repo/anet2016-cuhk$ python demo_server.py
Traceback (most recent call last):
  File "demo_server.py", line 7, in <module>
    from pyActionRec.action_classifier import ActionClassifier
  File "/media/weidawang/DATA/Repo/anet2016-cuhk/pyActionRec/__init__.py", line 1, in <module>
    from config import ANET_CFG
ModuleNotFoundError: No module named 'config'
```

**Comment by goat53wm** [comment]
> I can not open the demo website, anyone has the same issue ? So i try to run it locally, but i came across an error :
> 
> ```
> (base) weidawang@weidawang-TUF-Gaming-FX506LU-FX506LU:/media/weidawang/DATA/Repo/anet2016-cuhk$ python demo_server.py
> Traceback (most recent call last):
>   File "demo_server.py", line 7, in <module>
>     from pyActionRec.action_classifier import ActionClassifier
>   File "/media/weidawang/DATA/Repo/anet2016-cuhk/pyActionRec/__init__.py", line 1, in <module>
>     from config import ANET_CFG
> ModuleNotFoundError: No module named 'config'
> ```

hello,Did you solve it? How did you solve it?
